Repository metaopt/optree, pull requests merged in 2023-01, with the labels that each got.

#19 style: remove useless move found via clang-tidy
  include/treespec.h
Labels: cxx

#20 feat: add `clang-tidy` integration
  .clang-tidy
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint.yml
  .gitignore
  CONTRIBUTING.md
  CPPLINT.cfg
  Makefile
  include/registry.h
  include/treespec.h
  include/utils.h
  src/optree.cpp
  src/registry.cpp
  src/treespec/flatten.cpp
  src/treespec/traversal.cpp
  src/treespec/treespec.cpp
  src/treespec/unflatten.cpp
Labels: enhancement, cxx

#23 feat: add `doctest` integration
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  conda-recipe.yaml
  docs/conda-recipe.yaml
  docs/source/spelling_wordlist.txt
  optree/ops.py
  optree/registry.py
  optree/typing.py
  pyproject.toml
  tests/requirements.txt
Labels: documentation, enhancement

#24 feat(registry): raise a warning when registering subclasses of namedtuple
  docs/source/typing.rst
  include/utils.h
  optree/__init__.py
  optree/registry.py
  optree/typing.py
  pyproject.toml
  src/registry.cpp
  tests/test_registry.py
Labels: enhancement, cxx
