Repository metaopt/optree, pull requests merged in 2024-10, with the labels that each got.

#159 refactor: split implementation files and add more `inline` / `constexpr` / `noexcept` qualifiers
  .clang-format
  .clang-tidy
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/set_cibw_build.py
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  include/exceptions.h
  include/hashing.h
  include/mutex.h
  include/pymacros.h
  include/pytypes.h
  include/registry.h
  include/stdutils.h
  include/synchronization.h
  include/treespec.h
  src/CMakeLists.txt
  src/optree.cpp
  src/registry.cpp
  src/treespec/constructor.cpp
  src/treespec/flatten.cpp
  src/treespec/gc.cpp
  src/treespec/hashing.cpp
  src/treespec/richcomparison.cpp
  src/treespec/serialization.cpp
  src/treespec/traversal.cpp
  src/treespec/treespec.cpp
  src/treespec/unflatten.cpp
Labels: enhancement, cxx

#160 chore(typing): improve typing support for generic `PyTree[T]` and registry lookup / register functions
  CHANGELOG.md
  docs/source/spelling_wordlist.txt
  optree/ops.py
  optree/registry.py
  optree/typing.py
Labels: enhancement, py

#164 lint(dataclasses): fix annotation for `@optree.dataclasses.dataclass`
  .pre-commit-config.yaml
  optree/dataclasses.py
  optree/ops.py
Labels: bug, py

#165 lint(dataclasses): improve annotation for `optree.dataclasses.field()`
  optree/dataclasses.py
Labels: enhancement, py

#166 feat(typing): better annotation support for `PyTree[T]`
  CHANGELOG.md
  docs/source/conf.py
  docs/source/integration.rst
  optree/integration/__init__.py
  optree/typing.py
  pyproject.toml
  tests/integration/test_imports.py
Labels: documentation, enhancement, py, integration

#167 refactor!(include): move include directory `include/{ => optree}/*.h`
  .clang-format
  .clang-tidy
  .pre-commit-config.yaml
  CHANGELOG.md
  CMakeLists.txt
  include/optree/exceptions.h
  include/optree/hashing.h
  include/optree/optree.h
  include/optree/pymacros.h
  include/optree/pytypes.h
  include/optree/registry.h
  include/optree/stdutils.h
  include/optree/synchronization.h
  include/optree/treespec.h
  src/optree.cpp
  src/registry.cpp
  src/treespec/constructor.cpp
  src/treespec/flatten.cpp
  src/treespec/gc.cpp
  src/treespec/hashing.cpp
  src/treespec/richcomparison.cpp
  src/treespec/serialization.cpp
  src/treespec/traversal.cpp
  src/treespec/treespec.cpp
  src/treespec/unflatten.cpp
Labels: enhancement, cxx
