Repository metaopt/optree, pull requests merged in 2025-02, with the labels that each got.

#184 chore!(setup): enable CXX11 ABI in C++ extension
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  pyproject.toml
Labels: cxx

#188 feat(setup): support using system CMake
  CHANGELOG.md
  README.md
  pyproject.toml
  setup.py
Labels: enhancement

#189 feat: add shortcut module `optree.pytree` and `optree.treespec`
  CHANGELOG.md
  README.md
  docs/source/index.rst
  docs/source/ops.rst
  docs/source/pytree.rst
  docs/source/registry.rst
  docs/source/spelling_wordlist.txt
  docs/source/treespec.rst
  optree/__init__.py
  optree/pytree.py
  optree/treespec.py
  tests/test_shortcut.py
Labels: enhancement, py

#190 feat(registry): support lookup all registry entries in a `namespace`
  .github/workflows/lint.yml
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  Makefile
  README.md
  docs/source/pytree.rst
  docs/source/spelling_wordlist.txt
  docs/source/treespec.rst
  optree/ops.py
  optree/registry.py
  tests/test_registry.py
Labels: enhancement, py

#191 fix(setup): fix a cannot found `cmake` issue when install from source with venv'ed `cmake`
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/set_release.py
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  Makefile
  README.md
  optree/registry.py
  pyproject.toml
  setup.py
  tests/test_registry.py
Labels: bug

#193 fix(setup): fix a cannot found `cmake` issue when install from source without system `cmake`
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  setup.py
Labels: bug
