Repository metaopt/optree, pull requests merged in 2025-03, with the labels that each got.

#194 chore(workflows/build): enable PyPy 3.11 support
  .github/workflows/build.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
Labels: enhancement

#195 chore!(registry): remove deprecated key path APIs
  CHANGELOG.md
  docs/source/api.rst
  optree/__init__.py
  optree/registry.py
  pyproject.toml
  tests/test_prefix_errors.py
  tests/test_registry.py
Labels: py

#196 chore!(functools): remove deprecated `optree.Partial`
  .github/workflows/tests.yml
  CHANGELOG.md
  optree/__init__.py
  optree/functools.py
  pyproject.toml
  tests/test_functools.py
Labels: py

#197 feat(treespec): add method `PyTreeSpec.traverse`
  CHANGELOG.md
  CMakeLists.txt
  include/optree/treespec.h
  optree/_C.pyi
  src/optree.cpp
  src/treespec/traversal.cpp
  tests/test_ops.py
  tests/test_registry.py
Labels: cxx, py

#200 fix(tests): prepend `tests/` to `PYTHONPATH` in subprocess call in tests
  tests/helpers.py
  tests/test_treespec.py
Labels: bug, py

#201 chore(MANIFEST.in): include test suites in SDist
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  MANIFEST.in
  Makefile
Labels: enhancement, py

#202 deps: remove duplicate lint checks
  .flake8
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  conda-recipe.yaml
  docs/source/conf.py
  docs/source/spelling_wordlist.txt
  pyproject.toml
  tests/integration/test_imports.py
  tests/integration/test_jax.py
  tests/integration/test_numpy.py
  tests/requirements.txt
  tests/test_prefix_errors.py
  tests/test_treespec.py
Labels: enhancement, dependencies

#203 chore(setup): pass `build_temp` as string to `mkpath`
  setup.py
Labels: enhancement

#204 feat(tests): include branch coverage and add conditional pragmas
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  MANIFEST.in
  Makefile
  conda-recipe.yaml
  docs/source/api.rst
  docs/source/spelling_wordlist.txt
  optree/dataclasses.py
  optree/integration/__init__.py
  optree/integration/jax.py
  optree/integration/numpy.py
  optree/integration/torch.py
  optree/registry.py
  optree/typing.py
  pyproject.toml
  tests/.coveragerc
  tests/confcoverage.py
  tests/requirements.txt
  tests/test_ops.py
  tests/test_prefix_errors.py
  tests/test_treespec.py
Labels: enhancement

#205 feat(setup): detect `cmake` version and guard minimum version
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  optree/registry.py
  setup.py
Labels: enhancement, dependencies

#198 chore(workflows/tests): add Python 3.13t to test matrix
  .github/workflows/tests.yml
Labels: enhancement, dependencies
