Repository metaopt/optree, pull requests merged in 2025-05, with the labels that each got.

#209 refactor!: enforce naming convention of packages with singular and plural
  .pre-commit-config.yaml
  CHANGELOG.md
  docs/source/index.rst
  docs/source/integrations.rst
  docs/source/spelling_wordlist.txt
  include/optree/treespec.h
  optree/_C.pyi
  optree/__init__.py
  optree/accessor.py
  optree/accessors.py
  optree/dataclasses.py
  optree/functools.py
  optree/integration/__init__.py
  optree/integration/jax.py
  optree/integration/numpy.py
  optree/integration/torch.py
  optree/integrations/__init__.py
  optree/integrations/jax.py
  optree/integrations/numpy.py
  optree/integrations/torch.py
  optree/ops.py
  optree/registry.py
  optree/typing.py
  src/CMakeLists.txt
  src/optree.cpp
  src/treespec/constructors.cpp
  src/treespec/flatten.cpp
  src/treespec/treespec.cpp
  tests/integrations/test_imports.py
  tests/integrations/test_jax.py
  tests/integrations/test_numpy.py
  tests/integrations/test_torch.py
  tests/test_accessors.py
  tests/test_ops.py
  tests/test_typing.py
Labels: enhancement, py, integration

#212 feat(dataclasses): allow creating dataclass types in the global namespace
  CHANGELOG.md
  optree/dataclasses.py
  tests/test_dataclasses.py
Labels: enhancement, py, integration

#215 feat: dump build-time meta-information to C extension
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  conda-recipe.yaml
  include/optree/treespec.h
  optree/_C.pyi
  pyproject.toml
  src/optree.cpp
  tests/requirements.txt
  tests/test_ops.py
Labels: enhancement, cxx

#214 feat(PyTreeKind): use `pybind11::native_enum` to create enum class `PyTreeKind`
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/set_setup_requires.py
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  include/optree/pymacros.h
  include/optree/registry.h
  optree/_C.pyi
  pyproject.toml
  src/optree.cpp
  src/treespec/constructors.cpp
  src/treespec/flatten.cpp
  src/treespec/hashing.cpp
  src/treespec/richcomparison.cpp
  src/treespec/serialization.cpp
  src/treespec/traversal.cpp
  src/treespec/treespec.cpp
  src/treespec/unflatten.cpp
  tests/test_typing.py
Labels: enhancement, cxx, dependency, test-with-nightly-pybind11

#217 feat: use `pybind11::smart_holder` if available
  CHANGELOG.md
  CMakeLists.txt
  optree/_C.pyi
  src/optree.cpp
  src/treespec/gc.cpp
Labels: enhancement, cxx, dependency, test-with-nightly-pybind11

#218 test(treespec): add tests for `PyTreeSpec.{__new__,__init__}`
  .gitattributes
  .gitignore
  .pre-commit-config.yaml
  CMakeLists.txt
  include/optree/exceptions.h
  src/optree.cpp
  tests/test_treespec.py
  tests/test_typing.py
  tests/test_utils.py
Labels: enhancement, cxx

#222 feat(ops): add function `tree_partition`
  CHANGELOG.md
  docs/source/conf.py
  docs/source/ops.rst
  docs/source/pytree.rst
  docs/source/spelling_wordlist.txt
  optree/__init__.py
  optree/ops.py
  optree/pytree.py
  tests/test_ops.py
Labels: enhancement, py

#208 deps!(setuptools): migrate to `setuptools>=77` for PEP-639
  CHANGELOG.md
  pyproject.toml
Labels: dependency

#213 feat(pytree): add re-export API `optree.pytree.reexport(...)`
  .pre-commit-config.yaml
  docs/source/pytree.rst
  docs/source/spelling_wordlist.txt
  optree/__init__.py
  optree/pytree.py
  pyproject.toml
  tests/test_shortcut.py
Labels: enhancement, py, integration

#223 test: handle trace function change for `coverage`
  .github/workflows/tests-with-pydebug.yml
  .pre-commit-config.yaml
  optree/_C.pyi
  src/CMakeLists.txt
  src/optree.cpp
  tests/.coveragerc
  tests/confcoverage.py
  tests/helpers.py
  tests/test_concurrent.py
  tests/test_functools.py
  tests/test_ops.py
  tests/test_registry.py
  tests/test_treespec.py
  tests/test_typing.py
Labels: enhancement, py, thread-safety

#224 feat(workflows): save `pip` and `pre-commit` caches in CI
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tests-with-pydebug.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
Labels: enhancement, integration
